import { NextRequest, NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/dbConnect";
import { paymentModel } from "@/models/payment.model";
import { userModel } from "@/models/user.model";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/options";
import crypto from "crypto";

/**
 * Razorpay Payment Verification API
 * This API is called by the frontend after a successful payment in the checkout modal.
 * 
 * Flow:
 * 1. Receive razorpay_order_id, razorpay_payment_id, and razorpay_signature.
 * 2. Verify the signature using HMAC SHA256.
 * 3. If valid, update the payment status to 'success'.
 * 4. Enroll the user in the course.
 */

export async function POST(request: NextRequest) {
  try {
    await connectToDatabase();
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = await request.json();

    // 1. Authenticate User
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json(
        { success: false, message: "Unauthorized request" },
        { status: 401 }
      );
    }

    const user = session.user as any;

    // 2. Signature Verification
    // The signature is generated by hashing (order_id + "|" + payment_id) with the key_secret
    const body = razorpay_order_id + "|" + razorpay_payment_id;
    const expectedSignature = crypto
      .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET!)
      .update(body.toString())
      .digest("hex");

    const isSignatureValid = expectedSignature === razorpay_signature;

    if (!isSignatureValid) {
      // If signature is invalid, mark the payment as failed in our DB
      await paymentModel.findOneAndUpdate(
        { razorpayOrderId: razorpay_order_id },
        { status: "failed" }
      );
      
      return NextResponse.json(
        { success: false, message: "Invalid payment signature. Transaction failed." },
        { status: 400 }
      );
    }

    // 3. Update Payment Status in DB
    const payment = await paymentModel.findOneAndUpdate(
      { razorpayOrderId: razorpay_order_id },
      { 
        status: "success", 
        razorpayPaymentId: razorpay_payment_id,
        razorpaySignature: razorpay_signature 
      },
      { new: true }
    );

    if (!payment) {
      return NextResponse.json(
        { success: false, message: "Payment record not found" },
        { status: 404 }
      );
    }

    // 4. Enroll User in Course
    // We add the courseId to the user's courses array
    await userModel.findByIdAndUpdate(
      user._id,
      { $addToSet: { courses: payment.courseId } } // $addToSet ensures no duplicate enrollments
    );

    return NextResponse.json(
      { 
        success: true, 
        message: "Payment verified and enrollment successful!" 
      },
      { status: 200 }
    );

  } catch (error: any) {
    console.error("Error verifying payment:", error);
    return NextResponse.json(
      { success: false, message: "Internal server error during verification" },
      { status: 500 }
    );
  }
}
